use_frameworks!

platform :ios, '9.0'

target 'MobvoiTest_Example' do
  pod 'MobvoiTest', :path => '../'

  target 'MobvoiTest_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
